version: '3.8'
services:

  mariadb-master:
    build:
      context: .
      dockerfile: masterdb-dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./master_data:/var/lib/mysql
      - ./master.cnf:/etc/mysql/conf.d/master.cnf
      - ./master-mdb-entrypoint.sh:/bin/local/bin/master-mdb-entrypoint.sh
    command: ["./usr/local/bin/master-mdb-entrypoint.sh"]
    networks:
      vpcbr:
        ipv4_address: 172.21.0.2
    # Additional master configuration goes here

  mariadb-slave:
    build:
      context: .
      dockerfile: slavedb-dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_SLAVE_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_SLAVE_USER}
      MYSQL_PASSWORD: ${MYSQL_SLAVE_PASSWORD}
    volumes:
      - ./slave_data:/var/lib/mysql
      - ./slave.cnf:/etc/mysql/conf.d/slave.cnf
      - ./slave-mdb-entrypoint.sh:/bin/local/bin/slave-mdb-entrypoint.sh
    command: ["./usr/local/bin/slave-mdb-entrypoint.sh"]
    networks:
      vpcbr:
        ipv4_address: 172.21.0.5
    # Additional slave configuration goes here
    links:
      - mariadb-master:mariadb-master
    depends_on:
      - mariadb-master
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb-master
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PMA_USER: ${MYSQL_USER}
    ports: 
    - "8080:80"
    networks:
      vpcbr:
        ipv4_address: 172.21.0.3
    depends_on:
      - mariadb-master
      - mariadb-slave

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1

