version: '3.8'
services:
  web:
    build: .
    restart: unless-stopped 
    entrypoint: "./dev-entrypoint.sh"
    volumes:
      - ./:/var/www
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - database
#    labels:
#      - traefik.enable=true
#      - traefik.http.routers.webinfasi.rule=PathPrefix(`/infrasi`)
#      - traefik.http.routers.webinfasi.middlewares=strip-webinfasi-prefix
#      - traefik.http.middlewares.strip-webinfasi-prefix.stripprefix.prefixes=/infrasi
#      - traefik.http.routers.webinfasi.entrypoints=web
    networks:
      vpcbr:
        ipv4_address: 172.21.0.4

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
